import Link from "next/link";
import "./globals.css";
import { Cairo } from "next/font/google";

const cairo = Cairo({
  variable: "--cairo",
  style: "normal",
  subsets: ["latin", "latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={cairo.className + " bg-[#121212] text-white"}>
        <nav dir="ltr" className="py-6 bg-[#171717]">
          <div className="max-w-5xl mx-auto px-4">
            <Link href="/">
              <img src="/LOGO.svg" alt="" />
            </Link>
          </div>
        </nav>
        <div className="max-w-5xl mx-auto p-4">{children}</div>
      </body>
    </html>
  );
}
